baseURL = "https://mudows.github.io/"
title = "Diego Cezar | Portfolio"
theme = "introduction"
defaultContentLanguage = "pt-br"
enableRobotsTXT = true

[languages]

  [languages.pt-br]
    languageName = "PortuguÃªs"
    weight = 1
    contentDir = "content/pt-br"

  [languages.en]
    languageName = "English"
    weight = 2
    contentDir = "content/en"
